### ISSUE TITLE
Нужно предоставить макет дизайна сайта и согласовать это с заказчиком

### ISSUE THREAD

**Issue by KomaMix** [KomaMix/Cinema#1]

**Comment by tim-shadeling** [comment]
# Сведения из тех. задания:

### Порядок изменения и утверждения макета:
- Исполнитель разрабатывает макет продукта как минимум в двух вариантах и с наличием версий для ПК, планшетов и смартфонов.
- Заказчику предоставляются все варианты макета (которых минимум 2), из них выбирается один и отправляется на доработку.
- Заказчик может вносить правки в уже выбранный макет, если они также одобрены и Исполнителем.
- После доработки и внесения всех изменений макет закрепляется как рабочий. С этого момент Заказчик не в праве существенно изменять свои требования.

### Требования к интерфейсу:
- единый стиль для всех экранных форм;
- быстрое отображение экранных форм;
- единообразие оформления элементов управления как и на одной странцы, так и по всем страницам того же типа
- не более 3 основных цветов
- не более 2 шрифтов
- контентная зона (*что это?*) имеет вид сетки, в каждой ячейке которой находится постер с рейтингом контента.

Образец макета:
![Макеты](https://github.com/KomaMix/Cinema/assets/161817057/85917d47-f817-4128-8066-fc31ae55edd9)

Пожелания Заказчика:
>- главная страница должна быть разделена на несколько областей. Кнопки для входа и регистрации должны находиться в одной линии с логотипом;
>- верхний (шапка) и нижний (футер) колонтитул страниц, единый стиль оформления информационного наполнения;
>- область с главными новинками фильмов, сериалов, мультфильмов и т.п.
>- другая область должна представлять собой панель навигации для поиска и с перечислениями различных категорий;
>- еще одна область, основная, включает в себя различные подборки с постерами фильмов и т.п. Пример подборки: “по рейтингу”, “популярные”, “сейчас смотрят”;
