### ISSUE TITLE
Документация для текущих наработок (база знаний?)

### ISSUE THREAD

**Issue by KomaMix** [KomaMix/Cinema#11]

**Comment by tim-shadeling** [comment]
Сведения о страницах теперь содержатся [здесь](https://github.com/KomaMix/Cinema/issues/16).

Данные о внутреннем устройстве системы находятся [здесь](https://github.com/KomaMix/Cinema/blob/master/Cinema/Documentation/Documentation.docx).

**Comment by tim-shadeling** [comment]
Диаграмма классов будет строиться на этой [интерактивной доске](https://miro.com/app/board/uXjVKGs2PUk=/). Такой формат позволит удобно вносить изменения, пока не будет получен финальный вариант.

**Comment by tim-shadeling** [comment]
Техническое задание можно найти [здесь](https://github.com/KomaMix/Cinema/files/14795321/Kinonear.docx).

**Comment by tim-shadeling** [comment]
# Вклады участников:

## Тимур
- Разработка внешнего обустройства страниц.
- Ведение документации, за исключением данных о внутреннем устройстве системы. 
- Сбор данных в базу знаний.
- Подробное изучение технического задания и извлечение ключевых сведений оттуда.
- Общение с заказчиком.
- Корректировка планов

## Камиль
- Разработка внутреннего устройства системы и ее функционала.
- Создание и поддержка баз данных (БД пользователей, БД фильмов). Обеспечение сообщения баз данных с системой кинотеатра.
- Ведение документации насчет баз данных и функционала системы.
- Планирование рабочей нагрузки.
