### ISSUE TITLE
Интеграция базы данных в проект

### ISSUE THREAD

**Issue by KomaMix** [KomaMix/Cinema#2]
Нужно определить контекст данных для фильма и создать для этого контекста базу данных с тестовыми данными

**Comment by tim-shadeling** [comment]
Фильм может содержать следующие данные о себе:
- название;
- год выпуска:
- продолжительность;
- актерский состав;
- аннотация;
- стоимость просмотра;
- рейтинг;
- постер;
- слоган;
- кадры;
- трейлеры;
- ...

**Comment by KomaMix** [comment]
Определил контекст базы данных (скорее всего это тестовый контекст, и благодаря миграции базы данных очень легко будет это потом подправить, если будут изменения в проекте):
![image](https://github.com/KomaMix/Cinema/assets/133577667/b2493341-77f8-4c51-9737-e32ad170eaa3)
Пока все просто. Нет многих полей, которые должны быть.
Далее, для этих таблиц нужно определить классы для применение миграции базы данных и для удобного использования базы данных с помощью Entity Framework. Определение классов:
![image](https://github.com/KomaMix/Cinema/assets/133577667/ae1a94d2-92d7-4512-8e14-46e9a1ecc9ba)
![image](https://github.com/KomaMix/Cinema/assets/133577667/a0bec488-ffd1-4ef0-bf52-2602cdaf2dd3)

**Comment by KomaMix** [comment]
Далее, создал контекст базы данных:
![image](https://github.com/KomaMix/Cinema/assets/133577667/5a0cfdd7-2f19-4566-bb57-7b937a28426c)
С помощью этого класса можем изменять базу данных.
Дальше создал репозиторий для базы данных, чтобы взаимодействие с ней было безопасным:
![image](https://github.com/KomaMix/Cinema/assets/133577667/3663db1d-fac6-4b2c-a0cc-dcf493524cc4)
![image](https://github.com/KomaMix/Cinema/assets/133577667/e518a895-4f8b-46bb-9bc3-5c99e5836f12)
Правда пока нет репозитория для доступа к рейтингу фильмов (немного лень добавлять данные):
Так же заполнил базу данных данными:
![image](https://github.com/KomaMix/Cinema/assets/133577667/bd7c178f-abf1-4bb9-98ea-62ea18eaa6ad)

**Comment by KomaMix** [comment]
Для тестового задания пока этого хватит, поэтому можно этот вопрос закрыть
