### ISSUE TITLE
Определение первостепенных этапов разработки

### ISSUE THREAD

**Issue by KomaMix** [KomaMix/Cinema#3]
Нужно определить первостепенные этапы разработки, которые не зависят от макета и дизайна сайта

**Comment by tim-shadeling** [comment]
Можно разработать отдельный небольшой механизм, например: авторизация и учетные записи, поиск + фильтрация фильмов, комментарии к фильмам, подсчет рейтинга на основе оценок пользователей и др.

**Comment by KomaMix** [comment]
Добавлена поддержка базы данных. В дальнейших планах добавление функциональности авторизации и входа
